sudo: required

services:
  - docker

script:
  # Link Checks
  - |
    docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --white-list https://intra.niteo.co,https://github.com/niteoweb/operations,https://github.com/niteoweb/minisites,https://github.com/niteoweb/ebn,https://github.com/niteoweb/woocart,https://github.com/niteoweb/support,http://docs.niteo.co/,http://books.niteo.co/,http://videos.niteo.co/,https://github.com/issues/assigned,https://github.com/orgs/niteoweb/teams,https://apps.rackspace.com --skip-save-results `find . -name "*.md"`
