# Circle CI Configuration
# linkcheck validates all the links in all the markdown files.
# Validates only when a PR is created for the main branch.

version: 2.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make linkcheck
    branches:
      only:
        - main
